spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never